{% set name = "PyMca5" %}
{% set version = "5.7.1" %}

package:
  name: pymca
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62b1d9eaeb4d88bd4d8e13eb80705c8c4274175a7ffc5bb664571f4e9185e298

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - fisx >=1.1.6
    - h5py
    - numpy
    - pip
    - python
    - cython
  run:
    - fisx >=1.1.6
    - h5py
    - numpy
    - python

test:
  imports:
    - PyMca5

about:
  home: http://pymca.sourceforge.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mapping and X-Ray Fluorescence Analysis
  doc_url: http://www.silx.org/doc/PyMca/latest/tutorials.html

extra:
  recipe-maintainers:
    - tschoonj
