{% set name = "PyMca5" %}
{% set version = "5.5.2" %}

package:
  name: pymca
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2cfaa1561b3e32b7e2a5788add6394dbf14d72b475849f2e66e70529afab24b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  host:
    - fisx >=1.1.6
    - h5py
    - numpy
    - pip
    - python
    - cython
    - libglu  # [linux]
  run:
    - fisx >=1.1.6
    - h5py
    - numpy
    - python

test:
  imports:
    - PyMca5

about:
  home: http://pymca.sourceforge.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mapping and X-Ray Fluorescence Analysis
  doc_url: http://www.silx.org/doc/PyMca/latest/tutorials.html

extra:
  recipe-maintainers:
    - tschoonj
