{% set name = "PyMca5" %}
{% set version = "5.6.3" %}

package:
  name: pymca
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d0689cb5773b27f72090f475ee17a731fbc0ee4f046be9925cea006c0239618

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  host:
    - fisx >=1.1.6
    - h5py
    - numpy
    - pip
    - python
    - cython
    - libglu  # [linux]
  run:
    - fisx >=1.1.6
    - h5py
    - numpy
    - python

test:
  imports:
    - PyMca5

about:
  home: http://pymca.sourceforge.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mapping and X-Ray Fluorescence Analysis
  doc_url: http://www.silx.org/doc/PyMca/latest/tutorials.html

extra:
  recipe-maintainers:
    - tschoonj
