{% set name = "PyMca5" %}
{% set version = "5.8.4" %}

package:
  name: pymca
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a03c751f66ab5229f72405306a5ec92dafb518a40ebb45a73e691ab649d37412

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - fisx >=1.1.6
    - h5py
    - numpy
    - pip
    - python
    - cython
  run:
    - fisx >=1.1.6
    - h5py
    - matplotlib-base >1.0
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - PyMca5
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pymca.sourceforge.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mapping and X-Ray Fluorescence Analysis
  doc_url: http://www.silx.org/doc/PyMca/latest/tutorials.html

extra:
  recipe-maintainers:
    - tschoonj
